//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrpManagementSystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DotnetDBEntities : DbContext
    {
        public DotnetDBEntities()
            : base("name=DotnetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChannelTbl> ChannelTbls { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<RoleTbl> RoleTbls { get; set; }
        public virtual DbSet<loginTbl> loginTbls { get; set; }
    }
}
